### ISSUE TITLE
o mqtt está sendo fechado?

### ISSUE THREAD

**Issue by jcert** [jcert/autocouve#1]
https://github.com/jcert/autocouve/blob/dc1cb330f9ce891b5ed2c46a6efe9ceeb0f78a4a/node/init.lua#L35

isso deve ser chamado aí mesmo? ele vai tentar fechar a conexão mqtt

**Comment by mlbj** [comment]
essa versão é antiga, mas a chamada ainda existe na versão atual. Acredito que não deveria ser chamado mesmo, mas por algum motivo a conexão mqtt continua ativa

**Comment by mlbj** [comment]
corrigido
